// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeEmesnm5xTqMu1DA3ckTPPcNvgClb2Fc',
    appId: '1:941006401710:web:05c8957b304dc73e6ffd3f',
    messagingSenderId: '941006401710',
    projectId: 'test-sns-proj',
    authDomain: 'test-sns-proj.firebaseapp.com',
    storageBucket: 'test-sns-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd49nb7bLMxmqoN5OWLPfY4l-nxiBZ5QM',
    appId: '1:941006401710:android:f88296898bfcc9cf6ffd3f',
    messagingSenderId: '941006401710',
    projectId: 'test-sns-proj',
    storageBucket: 'test-sns-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFxNoSoPFdEyGt_VdNqMx9CRplPuAZunk',
    appId: '1:941006401710:ios:6e930e3d0b1f624d6ffd3f',
    messagingSenderId: '941006401710',
    projectId: 'test-sns-proj',
    storageBucket: 'test-sns-proj.appspot.com',
    iosClientId: '941006401710-irdqlj9i6ae88rp5ctbuvnmdltcm8du9.apps.googleusercontent.com',
    iosBundleId: 'com.example.testSnsProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFxNoSoPFdEyGt_VdNqMx9CRplPuAZunk',
    appId: '1:941006401710:ios:6e930e3d0b1f624d6ffd3f',
    messagingSenderId: '941006401710',
    projectId: 'test-sns-proj',
    storageBucket: 'test-sns-proj.appspot.com',
    iosClientId: '941006401710-irdqlj9i6ae88rp5ctbuvnmdltcm8du9.apps.googleusercontent.com',
    iosBundleId: 'com.example.testSnsProj',
  );
}
